#!/usr/bin/env python3
"""
One-time migration: strip computed fields from data/events/ YAMLs.

Rewrites each event file to contain only the 9 raw scraped fields,
discarding actors, issue_areas, weimar_relevant, trilateral_signal,
weimar_score, and extracted. Those will be regenerated by the pipeline
into data/enriched/.

Also deletes the three embedding JSON files so they are rebuilt from scratch.

Usage:
    python -m pipeline.migrate_strip --dry-run   # show what would change
    python -m pipeline.migrate_strip             # apply
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).parent.parent
EVENTS_DIR = ROOT / "data" / "events"

RAW_FIELDS = [
    "date",
    "type",
    "source_name",
    "title",
    "text",
    "source_url",
    "source_lang",
    "source_published_at",
    "ingested_at",
]

EMBEDDING_FILES = [
    ROOT / "data" / "embeddings.json",
    ROOT / "data" / "position_embeddings.json",
    ROOT / "data" / "goal_embeddings.json",
]


def strip_file(path: Path, dry_run: bool) -> bool:
    """Strip computed fields from one event YAML. Returns True if file changed."""
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except Exception as exc:
        print(f"  SKIP {path.name}: {exc}")
        return False

    if not data:
        return False

    raw_data = {k: data[k] for k in RAW_FIELDS if k in data}

    if set(data.keys()) == set(raw_data.keys()):
        return False  # already stripped

    if not dry_run:
        path.write_text(
            yaml.dump(raw_data, allow_unicode=True, sort_keys=False),
            encoding="utf-8",
        )
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description="Strip computed fields from raw event YAMLs")
    parser.add_argument("--dry-run", action="store_true", help="Show what would change without writing")
    args = parser.parse_args()

    files = sorted(EVENTS_DIR.glob("**/*.yaml"))
    print(f"{'DRY RUN — ' if args.dry_run else ''}Processing {len(files)} event files …")

    changed = skipped = 0
    for f in files:
        if strip_file(f, args.dry_run):
            print(f"  {'would strip' if args.dry_run else 'stripped'}: {f.relative_to(ROOT)}")
            changed += 1
        else:
            skipped += 1

    action = "Would strip" if args.dry_run else "Stripped"
    print(f"\n{action} {changed} files  ({skipped} already clean)")

    for emb_file in EMBEDDING_FILES:
        if emb_file.exists():
            if args.dry_run:
                print(f"  would delete: {emb_file.relative_to(ROOT)}")
            else:
                emb_file.unlink()
                print(f"  deleted: {emb_file.relative_to(ROOT)}")

    if not args.dry_run:
        print("\nDone. Next steps:")
        print("  uv run python -m pipeline.enrich   # rebuild data/enriched/")
        print("  uv run python -m pipeline.embed    # rebuild embeddings")
        print("  uv run python -m pipeline.render   # render site")


if __name__ == "__main__":
    main()
